project:
  type: website
  output-dir: docs

website:
  title: "Rosemary Juarez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog_settings.qmd
      - books.qmd
      - href: resources.qmd
        text: Resources
  page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, Rosemary Juarez"

format:
  html:
    theme:
       - styles.scss
    mainfont: Abel
    css: styles.css
    toc: true

editor: visual

